online_shop/core/urls.py
from django.urls import path

from core.views import home

urlpatterns = [
    path('', home, name="home"),
]

online_shop/online_shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("core.urls")),
    path('product/', include("product.urls")),
    path('order/', include("order.urls")),
    path('customer/', include("customer.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

online_shop/product/urls.py
from django.urls import path

from product.API import ProductListAPI, CreateCommentAPI
from product.views import StoreListView, CategoryListView, CategoryBasedProductListView, ProductDetailView, FrontCategories

urlpatterns = [
    path('store/', StoreListView.as_view(), name="store"),
    # path('CategoryProduct/<slug:slug>', CategoryBasedProductListView.as_view(), name="CategoryProduct"),
    path('CategoryProduct/<slug:slug>', FrontCategories.as_view(), name="CategoryProduct"),
    path('categories/', CategoryListView.as_view(), name="categories"),
    path('ProductDetail/<int:pk>', ProductDetailView.as_view(), name='ProductDetail'),

    # APIS
    # APIS
    # APIS

    path("ProductListAPI/", ProductListAPI.as_view(), name="ProductListAPI"),
    path("CommentCreateAPI/", CreateCommentAPI.as_view(), name="CreateCommentAPI")
]

online_shop/product/models.py
from django.core.validators import MinValueValidator
from django.db import models
from core.models import BaseModel
from customer.models import Customer


# Create your models here.

class Product(BaseModel):
    name = models.CharField(max_length=35, unique=True, help_text="Enter name of the product ")
    brand = models.ForeignKey(to='Brand', on_delete=models.SET_NULL, null=True)
    category = models.ForeignKey(to='Category', on_delete=models.CASCADE)
    description = models.TextField(max_length=500, default="Unknown")
    image = models.ImageField(blank=True, null=True, upload_to='static/images/product',
                              default='static/images/product/placeholder.png',
                              help_text="Upload photo of product here")
    in_stock = models.BooleanField(default=True)
    price = models.PositiveIntegerField(help_text="Enter price of product", validators=[MinValueValidator(0)])
    number_in_inventory = models.PositiveSmallIntegerField(default=1, validators=[MinValueValidator(0)])
    discount = models.OneToOneField(to='Discount', on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return self.name

    def check_in_stock(self):
        if self.number_in_inventory == 0:
            self.in_stock = False
            return self.in_stock
        else:
            return self.in_stock

    def add_order_item(self):
        if self.check_in_stock():
            self.number_in_inventory -= 1
            return True
        else:
            return False

    def remove_order_item(self):
        self.number_in_inventory += 1

        return self.number_in_inventory

    def after_discount_price(self):
        if self.discount is None:
            return self.price
        elif self.discount is not None:
            if self.discount.type == "percentage":
                discount_amount = (self.price * (100 - self.discount.value)) // 100
                self.after_dis_price = discount_amount
                if discount_amount > self.discount.max_discount:
                    raise "the discount is more than maximum amount for discount"
                else:
                    res = discount_amount
                    return res

            elif self.discount.type == "currency":
                if self.discount.value >= self.price:
                    raise "the discount is higher than price"
                else:
                    res = self.price - self.discount.value
                    return res

            else:
                raise "Error while precessing logic"
        else:
            raise "Error while precessing logic"


class Brand(BaseModel):
    name = models.CharField(max_length=20, help_text="name of a brand", unique=True)
    logo = models.ImageField(upload_to="static/images/logos")

    def __str__(self):
        return f"{self.name}"


class Category(BaseModel):
    class Meta:
        verbose_name_plural = "Categories"

    name = models.CharField(max_length=20, unique=True, help_text="Enter name of category")
    base_category = models.ForeignKey('self', on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return f"{self.name}"


class Discount(BaseModel):
    type = models.CharField(choices=[("percentage", "percentage"), ("currency", "currency")], max_length=10,
                            help_text="choose type of discount")
    value = models.PositiveIntegerField()
    max_discount = models.PositiveIntegerField(help_text="Enter max amount of discount", null=True, blank=True)

    def __str__(self):
        return f"{self.value} {self.type}"


class Comment(BaseModel):
    author = models.ForeignKey(to=Customer, on_delete=models.CASCADE)
    context = models.CharField(max_length=180)
    product = models.ForeignKey(to=Product, on_delete=models.CASCADE)

    def __str__(self):

        if self.author.user.first_name == '':
            return ' from Unknown'

        else:
            return f'from {self.author.user.first_name}'

online_shop/product/views.py
from django.views import generic
from product.models import Product, Category, Comment


class StoreListView(generic.ListView):
    model = Product
    template_name = "product/store.html"
    context_object_name = 'products'


class CategoryListView(generic.ListView):
    model = Category
    template_name = "product/categories.html"
    context_object_name = 'category'


class CategoryBasedProductListView(generic.ListView):
    model = Product
    template_name = "product/categorybasedproduct.html"
    context_object_name = 'products'

    def get_queryset(self):
        slug = self.kwargs.get('slug')
        query = Product.objects.filter(category__base_category__name=slug)
        return query


class FrontCategories(generic.ListView):
    model = Category
    template_name = "product/categorybasedproduct.html"
    context_object_name = 'categories'

    def get_queryset(self):
        slug = self.kwargs.get('slug')
        query = Category.objects.filter(base_category__name=slug)
        return query


class ProductDetailView(generic.DetailView):
    model = Product
    template_name = "product/ProductDetail.html"
    context_object_name = "product"
    pk_url_kwarg = "pk"

online_shop/templates/product/ProductDetail.html
{% extends 'core/main.html' %}
{% load static %}
{% block content %}

     {% for message in messages %}
         <div style="background-color: gray " class="sticky-top rounded mt-2 p-1 centered" id="message-cat">
             <h6 style="color: snow; ">{{ message }}</h6>
         </div>
     {% endfor %}




<div class="row">

    <div class="box-element product col-lg-8">
        <div class="col-lg-12 product centered">
            <h1><strong>{{ product.name }}</strong></h1>
        </div>
        <br>
        <br>
        <br>
        <h6 style=""> {{ product.description }}</h6>
    </div>

    <div class="box-element product col-lg-4">
                <img class="i" alt='1' src="{{product.image.url}}">
        <div class="box-element">
              {% if product.in_stock == True %}
                 <button data-product="{{ product.id }}" data-action="add" data-c ="{{ csrf_token }}" data-url="{% url 'AddToCart' %}" data-product-name='{{ product.name }}' class="btn btn-outline-secondary add-btn cart-update col-lg-12">Add to Cart</button>

            {% else %}
                <button class="btn btn-outline-secondary  col-lg-12" style="color: #c00101">Add to Cart</button>
            {% endif %}

            <br>
            <br>
            <h4 style=""><b>Brand:</b>   {{ product.brand }}</h4>
            <h4 style="display: inline-block; float:right;">   <img class="brand-logo" alt='Logo' src="{{product.brand.logo.url}}"></h4>

        {% if product.discount == None %}
            <h4 style=""><b>Price:</b>   ${{ product.price }}</h4>

        {% elif product.discount.type == "percentage" %}

             <h4 style="color: #C00101FF">% {{ product.discount.value }} Off</h4>
            <h4 style=""><b>Price:</b> ${{ product.after_discount_price }}  <s class="mr-3" style="color: #C00101FF; float: right">${{ product.price }}</s></h4>


        {% elif product.discount.type == 'currency' %}
              <h4 style="color: #C00101FF">-{{ product.discount.value }} </h4>
            <h4 style=""><b>Price:</b> ${{ product.after_discount_price }}  <s class="mr-4" style="color: #C00101FF; float: right">${{ product.price }}</s></h4>

        {% else %}
             <h4 style=""><b>Price:</b>something went wrong</h4>
        {% endif %}


            {% if product.in_stock == True %}
                <h4 style="color: green">In stock</h4>
            {% else %}
                <h4 style="color: #c00101">Out of stock</h4>
            {% endif %}

        </div>
    </div>
</div>

<div class="row">

    <div class="col-lg-12">
        <div class="box-element">
            <h3>Reviews:</h3>
            {% for comment in product.comment_set.all %}
                <div class="box-element mt-3"><h6>{{ comment }}</h6><br>
                                              <p>{{ comment.context }}</p>

                <p>{{ comment.create_timestamp }}</p>
                </div>


            {% endfor %}
        {% if request.user.is_authenticated %}


            <form class="mt-2">
                <div class="form-group">
                    <label for="commentCon">Comment</label>
                    <input type="text" class="form-control" id="commentCon" placeholder="Comment">
                     <small id="emailHelp" class="form-text text-muted">We won't share your phone number</small>
                </div>

                <button  type="submit" id="commentBtn" onclick="getComment({{ product.id }})" class="btn btn-dark col-lg-2"> Submit</button>
            </form>

        {% endif %}

        </div>
    </div>
</div>


<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/cart.js' %}"></script>

<script>
function getComment (product) {
    let comment = $('#commentCon').val()
     $.ajax({
            url: "{% url 'CreateCommentAPI' %}",
            method: 'POST',
            headers: {
                'X-CSRFTOKEN': '{{ csrf_token }}'

            },
            data: {
                'context': comment,
                'product': product
            },

        })
}

</script>

<script>
        x = $('#message-cat')
        x.fadeOut(2800)
    </script>



{% endblock %}

online_shop/templates/product/categories.html
{% extends 'core/main.html' %}
{% load static %}
{% block content %}

<div class="row">
{% for c in category%}
    {% if c.base_category is None %}

            <div class="col-lg-6">
                <div class="box-element product centered">
                    <h1><strong>{{ c.name }}</strong></h1>
                    <hr>
                    <hr>


                <a class="btn btn-outline-success add-btn col-lg-12 p-3" href="{% url 'CategoryProduct' slug=c %}">Visit Products</a>
                </div>
            </div>


    {% endif %}





{% endfor %}
</div>

{% endblock %}

online_shop/templates/product/categorybasedproduct.html
{% extends 'core/main.html' %}
{% load static %}

{% block content %}

     {% for message in messages %}
         <div style="background-color: gray " class="sticky-top rounded mt-2 p-1 centered" id="message-cat">
             <h6 style="color: snow; ">{{ message }}</h6>
         </div>
     {% endfor %}

    {% for category in categories %}
        <div class="box-element centered mt-3 mb-1">
            <h1>{{ category }}</h1>
        </div>

        <div class="row">
        {% for product in category.product_set.all %}

                    <div class="col-lg-4">

                        <img class="i" alt='1' src="{{product.image.url}}">


                        <div class="box-element product">
                            <h6><strong>{{ product.name }}</strong></h6>
                            {% if product.in_stock == True %}
                                <h6 style="color: #008000FF"><strong>In Stock</strong></h6>

                             {% else %}
                                <h6 style='color:#C00101FF'><strong>Out Of Stock</strong></h6>

                            {% endif %}
                            <hr>
                            {% if product.in_stock == True %}
                            <button data-product="{{ product.id }}" data-action="add" data-c ="{{ csrf_token }}" data-url="{% url 'AddToCart' %}" data-product-name='{{ product.name }}' class="btn btn-outline-secondary add-btn cart-update">Add to Cart</button>
                            {% else %}


                                <button class="btn btn-outline-danger" style="color: #c00101">Add to Cart</button>

                            {% endif %}
                            <a class="btn btn-outline-success add-btn" href="{% url 'ProductDetail' pk=product.pk %}">View</a>
                            {% if product.discount == None %}
                                <h4 style="display: inline-block; float:right;">${{ product.price }}</h4>

                            {% elif product.discount.type == 'percentage' %}
                                <h4  style="display: inline-block; float:right;"><b>${{ product.after_discount_price }}</b> <s style="color:#C00101FF;">${{ product.price }}</s></h4>

                            {% elif product.discount.type == 'currency' %}
                                <h4 style="display: inline-block; float:right;"><b>${{ product.after_discount_price }}</b>  <s style="color:#C00101FF;">${{ product.price }}</s></h4>

                            {%  else %}

                            {% endif %}

                        </div>
                    </div>

        {% endfor %}
        </div>
    {% endfor %}




<script src="{% static 'js/cart.js' %}"></script>


    <script>
        x = $('#message-cat')
        x.fadeOut(2800)
    </script>


{% endblock %}

online_shop/templates/product/store.html
{% extends "core/main.html" %}
{% load static %}
{% block content %}

 {% for message in messages %}
     <div style="background-color: gray" id="store-message" class=" sticky rounded mt-5 p-1 centered">
         <h6 style="color: snow; ">{{ message }}</h6>
     </div>
 {% endfor %}



<div class="sticky rounded mt-5 p-1 centered the_message"></div>




<div class="row" id="API-caller" data-Url="{% url 'ProductListAPI' %}"></div>

    <script type="text/javascript">
        product_list()


        function product_list(){
            let wrapper = document.getElementById('API-caller')
            let  url = document.getElementById('API-caller').getAttribute('data-url')
            fetch(url)
            .then((resp) => resp.json())

            .then(

                function (product){

                    for (let i of product){

                        let PK = i.id
                        function StockPart () {

                            if (i['in_stock'] === true) {

                                let s = `
                                 <h6 style="color: #008000FF"><strong>In Stock</strong></h6>
                                  <hr>
                                 <button data-product="${PK}" data-url="{% url 'AddToCart' %}" data-action="add" data-product-name=${i['name']} data-c ="{{ csrf_token }}" class="btn btn-outline-secondary add-btn cart-update">Add to Cart</button>
                                `
                                return s

                            } else if (i['in_stock'] === false) {

                                let s =
                                    `
                                    <h6 style='color:#C00101FF'><strong>Out Of Stock</strong></h6>
                                    <hr>
                                    <button class="btn btn-outline-danger" style="color: #c00101">Add to Cart</button>
                                    `
                                return s
                            }
                        }


                         function PricePart () {

                            if (i['discount'] === null) {

                                let p = `
                                <h4 style="display: inline-block; float:right;">$${ i['price'] }</h4>

                                `
                                return p

                            } else if (i['discount'] !== null) {

                                let p =

                                    `
                                    <h4 style="display: inline-block; float:right;"><b class="mr-3" ">${i['price']}</b><s style="color:#C00101FF">$${ i['price'] }</s></h4>
                                    `
                                {# ToDO add price after discout #}
                                return p
                            }
                        }

                        let item = `

                           <div class="col-lg-4">
                              <img class="i" alt='1' src="${i['image']}">

                              <div class="box-element product">

                                  <h6><strong>${ i.name }</strong></h6>
                                  ${StockPart()}
                                  <a class="btn btn-outline-success add-btn" href="http://127.0.0.1:8000/product/ProductDetail/${PK}">View</a>
                                  ${PricePart()}

                              </div>
                           <div>
                        `
                        wrapper.innerHTML += item

                    }
                }
            )
        }
    </script>

<script src="{% static 'js/cart.js' %}"></script>

 <script>
        x = $('#store-message')
        x.fadeOut(2800)
    </script>

{% endblock %}