online_shop/core/urls.py
from django.urls import path

from core.views import home

urlpatterns = [
    path('', home, name="home"),
]

online_shop/online_shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("core.urls")),
    path('product/', include("product.urls")),
    path('order/', include("order.urls")),
    path('customer/', include("customer.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

online_shop/core/models.py
from django.contrib.auth.models import AbstractUser, UserManager
from django.db import models


# Create your models here.
class BaseManager(models.Manager):

    def get_queryset(self):
        return super().get_queryset().filter(is_deleted=False)

    def archive(self):
        return super().get_queryset()


class BaseModel(models.Model):
    class Meta:
        abstract = True

    is_deleted = models.BooleanField(default=False)
    create_timestamp = models.DateTimeField(auto_now_add=True)
    modify_timestamp = models.DateTimeField(auto_now=True)
    delete_timestamp = models.DateTimeField(default=None, null=True, blank=True)

    objects = BaseManager()

    def logical_delete(self):
        self.is_deleted = True


class MyUserManager(UserManager):

    # def _create_user(self, username, email, password, **extra_fields):
    #     return super()._create_user(username, email, password, **extra_fields)

    def create_superuser(self, username=None, email=None, password=None, **extra_fields):
        username = extra_fields['phone']
        return super().create_superuser(username, email, password, **extra_fields)

    def create_user(self, username=None, email=None, password=None, **extra_fields):
        username = extra_fields['phone']
        return super().create_user(username, email, password, **extra_fields)


class User(AbstractUser):
    objects = MyUserManager()
    phone = models.CharField(max_length=13, unique=True)
    USERNAME_FIELD = 'phone'

    def save(self, *args, **kwargs):
        self.username = self.phone
        if User.objects.filter(id=self.id):
            self.set_password(self.password)
        super().save(*args, **kwargs)

online_shop/order/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from core.models import BaseModel
from customer.models import Customer, Address
from product.models import Product


# Create your models here.


class Cart(BaseModel):
    total_price = models.PositiveIntegerField(help_text="Total Price", default=0)
    final_price = models.PositiveIntegerField(help_text="Final Price", default=0)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    address = models.ForeignKey(Address, on_delete=models.SET_NULL, default=None, null=True)
    off_code = models.OneToOneField("OffCode", on_delete=models.CASCADE, null=True, blank=True)
    is_paid = models.BooleanField(default=False)

    def __str__(self):
        return f'Cart for: {self.customer.user.username}'

    def calculate_total_price(self):   ############# FRONT FUNCTION #############
        all_order_items = self.orderitem_set.all()
        for order in all_order_items:
            each_price = order.product.price
            price_for_all = each_price * order.how_many
            self.total_price += price_for_all
        return self.total_price

    def calculate_final_price(self):  ############# FRONT FUNCTION #############
        all_order_items = self.orderitem_set.all()
        if self.off_code is not None:
            for order in all_order_items:

                discounted_prices = order.sum_of_prices_after_discount()
                self.final_price += discounted_prices

            self.final_price = self.final_price * ((100 - self.off_code.value) // 100)

            return self.final_price

        else:
            self.final_price = 0
            for order in all_order_items:
                discounted_prices = order.sum_of_prices_after_discount()
                self.final_price += discounted_prices
            return self.final_price

    def check_is_paid(self):
        if self.is_paid is True:
            self.is_deleted = True
        else:
            pass

    def total_count(self):
        all_order_items = self.orderitem_set.all()
        count = 0
        for orders in all_order_items:
            count += orders.how_many
        return count


class OrderItem(BaseModel):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cart = models.ForeignKey(to=Cart, on_delete=models.CASCADE)
    how_many = models.PositiveSmallIntegerField(default=1, help_text="How many of this product do you need")

    def sum_of_prices_after_discount(self):
        res = self.product.after_discount_price() * self.how_many
        return res


class OffCode(BaseModel):
    the_code = models.CharField(max_length=10, help_text="Enter code for offer", unique=True)
    value = models.PositiveIntegerField(help_text="Enter code percentage for offer",
                                        validators=[MinValueValidator(1), MaxValueValidator(100)])
    is_active = models.BooleanField(default=True)
    how_many_use = models.PositiveSmallIntegerField(default=3, help_text="how many times do you want this code")

    def dis_activator(self):
        if self.how_many_use == 0:
            self.is_active = False
            self.is_deleted = True
        else:
            pass

online_shop/core/views.py
from django.shortcuts import render


# Create your views here.

def home(request):
    context = {}
    return render(request, "interface/home.html", context)

online_shop/templates/core/cdn.html
{% load static %}

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css"
      integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn"
      crossorigin="anonymous">
<link rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css">
<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">

online_shop/templates/core/footer.html
<!-- Footer -->
<footer class="page-footer font-small cyan darken-3 rounded-0" >

  <!-- Footer Elements -->
  <div class="container col-12 ">

      <!-- Grid row-->
    <div class="row">

      <!-- Grid column -->
      <div class="col-md-12 py-4 mt-2 icons">
        <div class="mb-5 ">

          <!-- Facebook -->
          <a class="whatsapp">
            <i class="fab fa-whatsapp fa-lg white-text mr-md-5 mr-3 fa-2x icon"> </i>
          </a>


          <!-- Twitter -->
          <a class="tw-ic">
            <i class="fab fa-twitter fa-lg white-text mr-md-5 mr-3 fa-2x icon"> </i>
          </a>

            <!--Instagram-->
          <a class="ins-ic" href="https://www.instagram.com/mahtor10/">
            <i class="fab fa-instagram fa-lg white-text mr-md-5 mr-3 fa-2x icon"> </i>
          </a>

          <!--Pinterest-->
          <a class="pin-ic" href="https://github.com/bloodyfork">
            <i class="fab fa-github fa-lg white-text fa-2x icon"> </i>
          </a>
        </div>
      </div>
      <!-- Grid column -->
    </div>
    <!-- Grid row-->
  </div>
  <!-- Footer Elements -->

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">POWERED BY:
    <a href="https://github.com/bloodyfork" id="creator">  BloodyFork</a>
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->

online_shop/templates/core/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <link rel="icon" type="image/x-icon" href="{% static 'images/frog.png' %}">
    <title>GROGGY SHOP</title>
    <meta charset="UTF-8">
    {% include "core/cdn.html" %}
    <script src="{% static 'js/jquery.js' %}"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1" />

{% block extrahead %}{% endblock %}
</head>
<body>
{% include "core/navbar.html" %}

<div class="container mt-2">
    {% block content %}

    {% endblock %}
</div>

<div>
{% include "core/footer.html" %}
</div>

{#<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"#}
{#        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"#}
{#        crossorigin="anonymous"></script>#}

<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.min.js"
        integrity="sha384-VHvPCCyXqtD5DqJeNxl2dtTyhF78xXNXdkwX1CZeRusQfRKp+tA7hAShOK/B/fQ2"
        crossorigin="anonymous"></script>

<script>const user = '{{ request.user }}'</script>

</body>
</html>

online_shop/templates/core/navbar.html
<!-- Navbar -->
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky" style="color: #3CB371">
  <a class="navbar-brand sticky" href="{% url 'home' %}"><img src="{% static 'images/frog.png' %}" alt="LOGO" style="width: 30px; height: 30px;"></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
       <li class="nav-item active">
        <a class="nav-link" href="{% url 'home'%}">Home</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'store'%}">Store</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'categories'%}">Category</a>
      </li>

      {% if user.is_authenticated %}
          <li class="nav-item active"></li>

       {% else %}
          <li class="nav-item active">
        <a class="nav-link" href="{% url 'register'%}">Sign-Up</a>
      </li>
      {% endif %}
    </ul>
   <div class="form-inline my-2 my-lg-0">
       {% if request.user.is_authenticated %}

           <a href="{% url 'profile' %} " class="btn btn-dark" style="margin-right: 10px; color: whitesmoke">view profile</a>
           <a href="{% url 'cart' %}">
            <i class="fa fa-shopping-cart fa-2x icon" aria-hidden="true" ></i>
       </a>
       <p id="cart-total">{{ request.user.customer.cart_set.last.total_count }}</p>

       {% else %}
           <a href="{% url 'login' %} " class="btn btn-dark" style="margin-right: 10px; color: whitesmoke;">Login</a>
           <a href="{% url 'cart' %}">
            <i class="fa fa-shopping-cart fa-2x icon" aria-hidden="true" ></i>
       </a>
       <p id="cart-total">0</p>

       {% endif %}
   </div>
  </div>
</nav>
<!-- End Navbar -->